---
- name: Install Python and Apache on Ubuntu EC2 instance
  hosts: webservers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure Python is installed
      apt:
        name: python3
        state: present

    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes
